version: 2.1
orbs:
  codecov: codecov/codecov@3.2.5
jobs:
  build:
    docker:
      - image: cimg/base:2023.07
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y cmake make gcc-10 g++-10 lcov gcovr
      - run:
          name: Build release
          command: |
              cmake -DCMAKE_BUILD_TYPE=Release .
              make
              cpack -G DEB
              cpack -G TGZ
      - store_artifacts:
          path: k-means-cpp
      - store_artifacts:
          path: k-means-cpp-*-Linux.tar.gz
      - store_artifacts:
          path: k-means-cpp.deb
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y cmake make gcc-10 g++-10 lcov gcovr
      - run:
          name: Build debug
          command: |
            cmake -DCMAKE_BUILD_TYPE=Debug .
            make
      - run:
          name: Generate coverage
          command: |
            make coverage
      - store_artifacts:
          path: coverage/index.html
      - codecov/upload:
          file: coverage/index.html
workflows:
  build_and_test:
    jobs:
      - build
      - test